owner: BlackMan985 # Ваш GitHub организация или имя пользователя
repo: blackgameshost.space # Название вашего репозитория

sites:
  - name: Панель
    url: https://panel.blackgameshost.space
  - name: Нода1
    url: https://n1.blackgameshost.space

status-website:
  cname: demo.upptime.js.org # Замените на ваш собственный домен, если он есть
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** — это открытый мониторинг доступности и страница статуса, полностью управляемая GitHub."
  introMessage: Это пример страницы статуса, которая использует **реальные** данные из нашего [GitHub репозитория](https://github.com/BlackMan985/blackgameshost.space). Не требуется сервер — только GitHub Actions, Issues и Pages. [**Получите свой бесплатно**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/BlackMan985/blackgameshost.space
